apiVersion: onecloud.yunion.io/v1
kind: Endpoint
metadata:
  name: endpoint-sample
spec:
  name: test
  url:
    host:
      reference:
        kind: VirtualMachine
        namespace: onecloud
        name: tm-tmzy
        fieldPath: Status.ExternalInfo.Ips[0]
    port: 8081
    prefix: test
